server:
  port: 8080

spring:
  application:
    name: withbuddy
  datasource:
    url: "jdbc:mysql://localhost/withbuddy"
    username: "root"
    password: ${DB_PASSWORD}


springdoc:
  swagger-ui:
    path: /swagger-ui.html