server:
  port: ${SERVER_PORT:8080}

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${SPRING_DB_URL}
    username: ${SPRING_DB_USERNAME}
    password: ${SPRING_DB_PASSWORD}
    driver-class-name: ${SPRING_DB_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
  data:
    redis:
      url: ${REDIS_URL}
  rabbitmq:
    uri: ${RABBITMQ_URL}
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never

jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_EXPIRATION:7200000}

ai:
  server:
    base-url: ${AI_SERVER_BASE_URL}

app:
  rabbitmq:
    exchange: ${RABBITMQ_EXCHANGE:withbuddy.exchange}
    queue-report: ${RABBITMQ_QUEUE_REPORT:withbuddy.report}
    queue-dlq: ${RABBITMQ_QUEUE_DLQ:withbuddy.report.dlq}

management:
  health:
    rabbit:
      enabled: false
    redis:
      enabled: false

